#===================================================================
# Spring Boot application configuration for development environment
#===================================================================

# Database configuration
MyServer:
  Database:
    HOST: localhost:5432
    DBNAME: to-do-list
    USER: postgres
    PASS: P@ssw0rd()SQL
MyConfig:
  Keycloak:
    CLIENTID: github-nimith-cc
    CLIENTSECRET: al8bR60BD5DpEAtTrnmCE3VPi0CHQBm7
    ISSUERURI: http://localhost:8080/realms/Nimith