#===================================================================
# Spring Boot application configuration for production environment
#===================================================================

# Database configuration
MyServer:
  Database:
    HOST: localhost:5432
    DBNAME: todolistdb
    USER: postgres
    PASS: admin123
